name: stories_lib
homepage: https://github.com/magnocasmor/stories_lib
description: Display and post stories like Instagram with Cloud Firestore and Firebase Storage.
version: 0.3.1+5

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.0.4
  exif: ^1.0.2
  image: ^2.1.4
  rxdart: ^0.23.1
  camera: ^0.5.8+2
  provider: ^4.0.5
  path_provider: ^1.6.7
  video_player: ^0.10.9+1
  firebase_core: ^0.4.3+2
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.0+1
  cached_network_image: ^2.0.0
  flutter_cache_manager: ^1.1.3
  flutter_image_compress: ^0.6.7
  video_compress: ^2.0.0
  multi_gesture_widget:
    git:
      url: https://github.com/magnocasmor/multi_gesture_widget.git
      ref: master
    version: ^0.0.1
  equatable: ^1.2.0

dev_dependencies:
  build_runner: ^1.7.3
  test: ^1.6.1
