name: stories_lib
homepage: https://github.com/magnocasmor/stories_lib
description: Display and post stories like Instagram with Cloud Firestore.
version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.23.1
  provider: ^4.0.5
  video_player: ^0.10.9+1
  skeleton_text: ^1.0.0
  firebase_core: ^0.4.3+2
  cloud_firestore: ^0.13.0+1
  cached_network_image: ^2.0.0
  flutter_cache_manager: ^1.1.3

dev_dependencies:
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
  test: ^1.6.1
